## Problem Statement

Q.1 Write a function to compute 5/0 and use try/except to catch the exceptions.

In [1]:
def divide(x, y): 
    try: 
        # Floor Division : Gives only Fractional Part as Answer 
        result = x // y 
        print("Yeah ! Your answer is :", result) 
    except ZeroDivisionError: 
        print("Sorry ! You are dividing by zero ") 
divide(5, 0) 

Sorry ! You are dividing by zero 


Q.2 Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

    Hint: Subject,Verb and Object should be declared in the program as shown below.
    subjects=["Americans ","Indians"]
    verbs=["play","watch"]
    objects=["Baseball","Cricket"]

    Output should come as below:
    Americans play Baseball.
    Americans play Cricket.
    Americans watch Baseball.
    Americans watch Cricket.
    Indians play Baseball.
    Indians play Cricket.
    Indians watch Baseball.
    Indians watch Cricket.

In [2]:
subject=["Americans", "Indians"]
verb=["Play", "watch"]
obj=["Baseball","cricket"]

sentence_list = [(sub+" "+ vb + " " + ob) for sub in subject for vb in verb for ob in obj]
for sentence in sentence_list:
 print (sentence)

Americans Play Baseball
Americans Play cricket
Americans watch Baseball
Americans watch cricket
Indians Play Baseball
Indians Play cricket
Indians watch Baseball
Indians watch cricket


Q.3 Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

    HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde.

In [9]:
import numpy as np
x = np.array([1, 2, 3, 5])
N = 3
np.vander(x, N)

print(np.column_stack([x**(N-1-i) for i in range(N)]))

x = np.array([1, 2, 3, 5])
print(np.vander(x))

print(np.vander(x, increasing=True))


[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [25  5  1]]
[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]
[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   5  25 125]]
